"""
Database model for adjustment records.

Represents financial adjustments (credits, debits, corrections).
Traceable to payment_id and case_id.

Adjustment sign convention:
  - Positive amount = credit (increases settlement)
  - Negative amount = debit (decreases settlement)
"""

from sqlalchemy import Column, String, Integer, DateTime, Index
from datetime import datetime

from app.database.database import Base


class Adjustment(Base):
    """
    Database model for adjustment records.

    Stores adjustment events generated by the synthetic data generator
    or observed in real financial data.

    Ground truth labels are NOT stored here.
    """

    __tablename__ = "adjustments"

    id = Column(String, primary_key=True)  # adjustment_id, e.g. ADJ-000001
    payment_id = Column(String, nullable=False, index=True)  # FK to Payment
    case_id = Column(String, nullable=True, index=True)  # FK to Case if applicable
    merchant_id = Column(String, nullable=True, index=True)  # FK to Merchant

    # Financial amount (in paise, integer)
    # Positive = credit, Negative = debit
    amount = Column(Integer, nullable=False)

    # Adjustment type
    adjustment_type = Column(String, nullable=False)  # AdjustmentType enum value

    # Metadata
    created_at = Column(DateTime, default=datetime.utcnow)

    # Indexes for efficient querying
    __table_args__ = (
        Index("ix_adjustments_payment_case", "payment_id", "case_id"),
    )
