"""
Database model for refund records.

Represents refunds issued against payment transactions.
Traceable to payment_id and case_id.
"""

from sqlalchemy import Column, String, Integer, DateTime, Index
from datetime import datetime

from app.database.database import Base


class Refund(Base):
    """
    Database model for refund records.

    Stores refund events generated by the synthetic data generator
    or observed in real financial data.

    Ground truth labels are NOT stored here.
    """

    __tablename__ = "refunds"

    id = Column(String, primary_key=True)  # refund_id, e.g. REF-000001
    payment_id = Column(String, nullable=False, index=True)  # FK to Payment
    case_id = Column(String, nullable=True, index=True)  # FK to Case if applicable
    merchant_id = Column(String, nullable=True, index=True)  # FK to Merchant

    # Financial amount (in paise, integer)
    amount = Column(Integer, nullable=False)

    # Status
    status = Column(String, nullable=False, default="PROCESSED")  # RefundStatus

    # Timestamps
    refund_timestamp = Column(DateTime, nullable=True)
    created_at = Column(DateTime, default=datetime.utcnow)

    # Indexes for efficient querying
    __table_args__ = (
        Index("ix_refunds_payment_case", "payment_id", "case_id"),
    )
