"""
Database model for tax records.

Represents taxes applied to payment transactions.
Traceable to payment_id and case_id.
"""

from sqlalchemy import Column, String, Integer, DateTime, Index
from datetime import datetime

from app.database.database import Base


class Tax(Base):
    """
    Database model for tax records.

    Stores tax events generated by the synthetic data generator
    or observed in real financial data.

    Ground truth labels are NOT stored here.
    """

    __tablename__ = "taxes"

    id = Column(String, primary_key=True)  # tax_id, e.g. TAX-000001
    payment_id = Column(String, nullable=False, index=True)  # FK to Payment
    case_id = Column(String, nullable=True, index=True)  # FK to Case if applicable
    merchant_id = Column(String, nullable=True, index=True)  # FK to Merchant

    # Financial amount (in paise, integer)
    amount = Column(Integer, nullable=False)

    # Tax type
    tax_type = Column(String, nullable=False)  # TaxType enum value

    # Metadata
    created_at = Column(DateTime, default=datetime.utcnow)

    # Indexes for efficient querying
    __table_args__ = (
        Index("ix_taxes_payment_case", "payment_id", "case_id"),
    )
